refactor: Restructured workflow file

diff --git a/.github/workflows/cloud-deploy.yml b/.github/workflows/cloud-deploy.yml
--- a/.github/workflows/cloud-deploy.yml
+++ b/.github/workflows/cloud-deploy.yml
@@ -197,14 +197,51 @@ jobs:
     - name: Terraform Apply
       run: terraform apply -auto-approve tfplan
 
-    # Terraform Plan Approve for Prod
-    - name: Tfplan Transfer
-      working-directory: .
-      run: 
-        cp staging/tfplan production/tfplan
+  terraform-production:
+    name: 'Terraform Apply Production'
+    if: github.ref == 'refs/heads/main' && needs.terraform-apply.result == 'success'
+    runs-on: ubuntu-latest
+    environment: production
+    needs: [terraform-apply]
+    defaults:
+      run:
+        working-directory: production
+    
+    steps:
+      
+    
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v4
 
-    - name: Terraform Apply Production
-      working-directory: production
+    # Install the latest version of the Terraform CLI
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v3
+      with:
+        terraform_wrapper: false
+
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      run: terraform init
+
+    # Generates an execution plan for Terraform
+    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    - name: Terraform Plan
+      id: tf-plan
+      run: |
+        export exitcode=0
+        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+
+        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+        
+        if [ $exitcode -eq 1 ]; then
+          echo Terraform Plan Failed!
+          exit 1
+        else 
+          exit 0
+        fi
+
+    - name: Terraform Apply Product
       run: 
         terraform apply -auto-approve tfplan
 
@@ -214,6 +251,6 @@ jobs:
 
   terraform-rollback:
     name: 'Terraform Apply Production Rollback'
+    if: github.ref == 'refs/heads/main' && needs.terraform-production.result == 'failure'
     needs: [terraform-apply]
-    if: ${{ github.ref == 'refs/heads/main' && needs.terraform-apply.result == 'failure' }}
     uses: ./.github/workflows/clouddeploy-failsafe.yml
