fix: Validated terraform config. ready to run

diff --git a/.github/workflows/cloud-deploy.yml b/.github/workflows/cloud-deploy.yml
--- a/.github/workflows/cloud-deploy.yml
+++ b/.github/workflows/cloud-deploy.yml
@@ -298,66 +298,66 @@ jobs:
   #     - name: Terraform Apply
   #       run: terraform apply -auto-approve tfplan
 
-  # terraform-production:
-  #   name: 'Terraform Apply Production'
-  #   # if: github.ref == 'refs/heads/main' && needs.terraform-apply.result == 'success'
-  #   runs-on: ubuntu-latest
-  #   environment: production
-  #   needs: [terraform-test]
-  #   defaults:
-  #     run:
-  #       working-directory: production
-  #   env:
-  #     ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
-  #     ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
-  #     ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
-  #     ARM_USE_AZUREAD: true
-  #     ARM_USE_CLI: true
+  terraform-production:
+    name: 'Terraform Apply Production'
+    # if: github.ref == 'refs/heads/main' && needs.terraform-apply.result == 'success'
+    runs-on: ubuntu-latest
+    environment: production
+    needs: [terraform-test]
+    defaults:
+      run:
+        working-directory: production
+    env:
+      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
+      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
+      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
+      ARM_USE_AZUREAD: true
+      ARM_USE_CLI: true
       
-  #   steps:
-  #     - name: Azure login
-  #       uses: azure/login@v2
-  #       with:
-  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
-  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+    steps:
+      - name: Azure login
+        uses: azure/login@v2
+        with:
+          client-id: ${{ secrets.AZURE_CLIENT_ID }}
+          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     
-  #     # Checkout the repository to the GitHub Actions runner
-  #     - name: Checkout
-  #       uses: actions/checkout@v4
+      # Checkout the repository to the GitHub Actions runner
+      - name: Checkout
+        uses: actions/checkout@v4
 
-  #     # Install the latest version of the Terraform CLI
-  #     - name: Setup Terraform
-  #       uses: hashicorp/setup-terraform@v3
-  #       with:
-  #         terraform_wrapper: false
+      # Install the latest version of the Terraform CLI
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_wrapper: false
 
-  #     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-  #     - name: Terraform Init
-  #       run: terraform init -backend-config="container_name=${{ vars.AZURE_STORAGE_CONTAINER_NAME }}" -backend-config="storage_account_name=${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}"
+      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+      - name: Terraform Init
+        run: terraform init -backend-config="container_name=${{ vars.AZURE_STORAGE_CONTAINER_NAME }}" -backend-config="storage_account_name=${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}"
 
-  #     # Generates an execution plan for Terraform
-  #     # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
-  #     - name: Terraform Plan
-  #       id: tf-apply-plan
-  #       run: |
-  #         export exitcode=0
-  #         terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+      # Generates an execution plan for Terraform
+      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+      - name: Terraform Plan
+        id: tf-apply-plan
+        run: |
+          export exitcode=0
+          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
 
-  #         echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
           
-  #         if [ $exitcode -eq 1 ]; then
-  #           echo Terraform Plan Failed!
-  #           exit 1
-  #         else 
-  #           exit 0
-  #         fi
+          if [ $exitcode -eq 1 ]; then
+            echo Terraform Plan Failed!
+            exit 1
+          else 
+            exit 0
+          fi
 
-  #     - name: Terraform Apply Product
-  #       if: steps.tf-apply-plan.outputs.exitcode == 2
-  #       run: 
-  #         terraform apply -auto-approve tfplan
+      - name: Terraform Apply Product
+        if: steps.tf-apply-plan.outputs.exitcode == 2
+        run: 
+          terraform apply -auto-approve tfplan
 
-  #     - name: Terraform Output to file
-  #       run: 
-  #         terraform output -raw -json | jq '.' > outputs.json
+      - name: Terraform Output to file
+        run: 
+          terraform output -raw -json | jq '.' > outputs.json
