fix: Dropped first plan

diff --git a/.github/workflows/cloud-deploy.yml b/.github/workflows/cloud-deploy.yml
--- a/.github/workflows/cloud-deploy.yml
+++ b/.github/workflows/cloud-deploy.yml
@@ -26,73 +26,73 @@ permissions:
     
       
 jobs:
-  terraform-test:
-    name: 'Terraform Test'
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: production
-    env:
-      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
-      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
-      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
-      ARM_USE_AZUREAD: true
-      ARM_USE_CLI: true
+  # terraform-test:
+  #   name: 'Terraform Test'
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       working-directory: production
+  #   env:
+  #     ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
+  #     ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
+  #     ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
+  #     ARM_USE_AZUREAD: true
+  #     ARM_USE_CLI: true
 
-    outputs:
-      prodPresent: ${{ steps.tf-plan.outputs.prodPresent }}
-      envEmpty: ${{ steps.tf-plan.outputs.prodPresent }}
+  #   outputs:
+  #     prodPresent: ${{ steps.tf-plan.outputs.prodPresent }}
+  #     envEmpty: ${{ steps.tf-plan.outputs.prodPresent }}
       
 
-    steps:
-      - name: Azure login
-        uses: azure/login@v2
-        with:
-          client-id: ${{ secrets.AZURE_CLIENT_ID }}
-          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  #   steps:
+  #     - name: Azure login
+  #       uses: azure/login@v2
+  #       with:
+  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
+  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     
       
-      # Checkout the repository to the GitHub Actions runner
-      - name: Checkout
-        uses: actions/checkout@v4
+  #     # Checkout the repository to the GitHub Actions runner
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      # Install the latest version of the Terraform CLI
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_wrapper: false
+  #     # Install the latest version of the Terraform CLI
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v3
+  #       with:
+  #         terraform_wrapper: false
 
-      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-      - name: Terraform Init
-        run: terraform init
+  #     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+  #     - name: Terraform Init
+  #       run: terraform init
 
-      # Generates an execution plan for Terraform
-      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
-      - name: Terraform Plan
-        id: tf-plan
-        run: |
-          export exitcode=0
-          terraform plan -detailed-exitcode -no-color || export exitcode=$?
+  #     # Generates an execution plan for Terraform
+  #     # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+  #     - name: Terraform Plan
+  #       id: tf-plan
+  #       run: |
+  #         export exitcode=0
+  #         terraform plan -detailed-exitcode -no-color || export exitcode=$?
           
-          if [ $exitcode -eq 2 ]; then
-            echo "Production folder not present or has changes."
-            echo "prodPresent=true" >> $GITHUB_OUTPUT
-          else
-            echo "No changes in Production folder."
-            echo "prodPresent=false" >> $GITHUB_OUTPUT
-          fi
+  #         if [ $exitcode -eq 2 ]; then
+  #           echo "Production folder not present or has changes."
+  #           echo "prodPresent=true" >> $GITHUB_OUTPUT
+  #         else
+  #           echo "No changes in Production folder."
+  #           echo "prodPresent=false" >> $GITHUB_OUTPUT
+  #         fi
           
-          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+  #         echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
           
-          echo "exitcode=$exitcode"
+  #         echo "exitcode=$exitcode"
 
-          if [ $exitcode -eq 1 ]; then
-            echo Terraform Plan Failed!
-            exit 1
-          else 
-            exit 0
-          fi
+  #         if [ $exitcode -eq 1 ]; then
+  #           echo Terraform Plan Failed!
+  #           exit 1
+  #         else 
+  #           exit 0
+  #         fi
 
 
       
@@ -100,8 +100,8 @@ jobs:
   terraform-plan:
     name: 'Terraform Plan'
     runs-on: ubuntu-latest
-    needs: [terraform-test]
-    if: needs.terraform-test.outputs.prodPresent == 'true'
+    # needs: [terraform-test]
+    # if: needs.terraform-test.outputs.prodPresent == 'true'
     defaults:
       run:
         working-directory: staging
